"""FileType -> (reader, loader) mapping.

Shared core: do not edit this file to add a company. A company registers
itself by calling `register()` from its own package on import.
"""
from app.ingestion.base import BaseReader, BaseLoader

_REGISTRY: dict[str, tuple[type[BaseReader], type[BaseLoader]]] = {}


def register(file_type, reader, loader):
    """Bind a FileType to its reader and loader classes."""
    _REGISTRY[file_type] = (reader, loader)


def get_handlers(file_type):
    """Return (reader_cls, loader_cls) for a FileType, or raise if unknown."""
    if file_type not in _REGISTRY:
        raise KeyError(f"No handlers registered for FileType {file_type!r}")
    return _REGISTRY[file_type]
